ardanlabs/gotraining

- 01-language_syntax/04-constants/example1/example1.go
- 03-methods_interfaces_embedding/01-methods/exercises/exercise1/exercise1.go
> Small changes to exercises to accomodate bugs found during training

- 07-concurrency_channels/02-race_conditions/readme.md
- 09-testing/03-caching/readme.md
> Minor typo correction

- 12-http/example3/main.go
- 12-http/example3/template/index.html
I know we need to talk about these changes :)
> Changes for readability. Also to maintain safe slice access.

- 13-http/api/handlers/users.go
- 13-http/api/main.go
- 13-http/api/models/users.go
- 13-http/api/routes/routes.go
- 13-http/api/services/users.go
- 13-http/api/tests/endpoint/users_test.go
- 13-http/api/tests/services/users_test.go
Replaces references to old http directory to match the new one.
> Fix http imports to match path

- 13-http/api/models/models.go
- 13-http/api/models/users.go
Model validations are now provided by the fantastic: github.com/bluesuncorp/validator
It really simplified the validation methods.
> Use struct tags for model validations

- topics/interfaces/README.md
Fixes link to polymorphism example in README.md
> Update README.md, fix link to polymorphism example

- topics/interfaces/README.md
- topics/interfaces/exercises/template1/template1.go
The response for this exercise uses new values to call the sayHello function, however the template directions was not really asking it and might use the old variables that was just created. I felt it would be better if that is made explicit.
> Updating exercise template and playground link

- topics/variables/README.md
Thanks for the training in Amsterdam Bill!
> Found a typo

- topics/slices/README.md
- topics/slices/example3/example3.go
Also updated the comment in the playground example
> Fix minor typo in comments for slices/example3.go

- topics/testing/example3/example3_test.go
> Modify syntax in example3

- topics/composition/README.md
- topics/composition/example6/example6.go
The comments say we are implementing the Mover interface but really
we're implementing `fmt.Stringer`. I updated the comments and changed
the strings that a car or cloud might produce.
> Change composition example 6

- reading/design_guidelines.md
- topics/composition/README.md
A few trivial fixups observed in class today.
> small fixups

- topics/profiling/README.md
> Minor typo

- topics/profiling/README.md
The link to download boom was broken.
> Fix link to boom in README.md

- courses/ultimate/concurrency/README.md
Simple fix of a typo (unless sarcastic concurrency joke, then I just created a declined pull request).
> Fix repeat of "understand the" in intro paragraph

- topics/goroutines/exercises/exercise1/exercise1.go
- topics/goroutines/exercises/template1/template1.go
These are minor updates, but when doing this exercise, I found these elements to be a little jarring for the expectation of the exercise.
> Updating template text to be more clear & match answer.

- topics/profiling/blocking/blocking_test.go
Now when running the test a plot called `latencies.png` is created.
> Add plot to the blocking example

- courses/web/README.md
- topics/web/apis/README.md
- topics/web/context/README.md
- topics/web/context/example1/main.go
- topics/web/context/example1/main_test.go
- topics/web/context/example2/main.go
- topics/web/context/example2/main_test.go
- topics/web/posts/example3/main.go
- topics/web/posts/example3/main_test.go
- topics/web/sockets/README.md
- topics/web/sockets/example1/main.go
- topics/web/sockets/example1/main_test.go
- topics/web/sockets/example1/refresh.yml
- topics/web/sockets/example1/static/app.js
- topics/web/sockets/example1/static/index.html
- topics/web/sockets/example1/static/styles.css
- topics/web/sockets/example2/main.go
- topics/web/sockets/example2/main_test.go
- topics/web/sockets/example2/refresh.yml
- topics/web/sockets/example2/static/app.js
- topics/web/sockets/example2/static/index.html
- topics/web/sockets/example2/static/styles.css
> Context & Sockets

- topics/language/struct_types/advanced/example1/example1.go
* fixes paths in `structlayout` commands
> Comments fix

- topics/data_science/classification_kNN/example1/example1.go
- topics/data_science/dimensionality_reduction/example1/example1.go
- topics/data_science/dimensionality_reduction/example2/example2.go
- topics/data_science/dimensionality_reduction/example3/example3.go
- topics/data_science/dimensionality_reduction/exercises/exercise1/exercise1.go
- topics/data_science/dimensionality_reduction/exercises/template1/template1.go
- topics/data_science/regression/example1/example1.go
- topics/data_science/regression/example2/example2.go
- topics/data_science/stats_measures/example1/example1.go
- topics/data_science/stats_measures/example2/example2.go
- topics/data_science/stats_measures/example4/example4.go
- topics/data_science/stats_measures/exercises/exercise1/exercise1.go
- topics/data_science/stats_measures/exercises/template1/template1.go
- topics/data_science/stats_vizualization/example2/example2.go
- topics/data_science/stats_vizualization/example4/example4.go
Based on advice from Alex, changing the extraction of floats from dataframes.
> Gota changes

- topics/data_science/caching/example1/example1.go
- topics/data_science/caching/example2/example2.go
- topics/data_science/caching/exercises/exercise1/exercise1.go
- topics/data_science/caching/exercises/template1/template1.go
- topics/data_science/json/example1/example1.go
- topics/data_science/json/example2/example2.go
- topics/data_science/json/exercises/exercise1/exercise1.go
- topics/data_science/json/exercises/template1/template1.go
- topics/data_science/matrix_operations/example2/example2.go
- fixes some issues with the JSON and caching examples.
> Fix http handling, json examples

- topics/data_science/integrity/example2/example2.go
- topics/data_science/integrity/example4/example4.go
csv.NewReader has a built in bufio reader. So there's no need to wrap other readers you pass into it.
> Remove using bufio reader

- courses/data_science/TOOLING.md
- topics/data_science/sql/README.md
- topics/data_science/sql/example1/example1.go
- topics/data_science/sql/example2/example2.go
- topics/data_science/sql/example3/example3.go
- topics/data_science/sql/example4/example4.go
- topics/data_science/sql/exercises/exercise1/exercise1.go
- topics/data_science/sql/exercises/exercise2/exercise2.go
- topics/data_science/sql/exercises/template1/template1.go
- topics/data_science/sql/exercises/template2/template2.go
- update data science sql stuff to postgres
> Update database topics to postgres

- topics/data/caching/exercises/exercise1/exercise1.go
the example will not run otherwise
> convert the string instead of casting

- README.md
I went with a little bit of humor. Let me know what you think.
> Add my bio to the README

- topics/language/methods/example3/example3.go
Made a small spelling correction on line 39, changed Complier to Compiler
> Made a small spelling correction on line 39

- topics/web/posts/README.md
- topics/web/posts/example3/main.go
- topics/web/posts/example3/main_test.go
- topics/web/posts/example4/main_test.go
1. Example 3 says it was about parsing JSON but in the code it really isn't. It's about parsing form data into structs using `github.com/gorilla/schema`. I updated the descriptions to make that more clear.
2. The test for Example 4 passed but it wasn't testing what it thought. It was declaring an empty `[]byte` then calling `.Read` on the files to populate the slices but `Read` will only read up to the length of the slice (which was 0) so the tests would always pass even if the uploaded file was empty or corrupt.
> Review topics/web/posts

- .travis.yml
- README.md
- starter-kits/http/cmd/apid/tests/user_test.go
- topics/web/auth/example2/main_test.go
First I fixed some problems with the starter kit tests so we had a passing build. Next I added a travis file to install deps and run tests. I am using a little bash script to run tests for any package that contains a `*_test.go` file. I would use `go test ./...` but there are some examples that aren't intended to compile. This method tests the packages that need it and will expand as new packages with tests are added.
> Ensure passing tests with Travis CI

- topics/go/design/composition/README.md
- topics/go/design/composition/mocking/example1/example1.go
- topics/go/packages/encoding/example2/example2.go
- topics/go/packages/encoding/exercises/exercise1/exercise1.go
- topics/go/packages/io/advanced/example1/example1.go
- topics/go/packages/reflection/README.md
- topics/go/profiling/README.md
- topics/go/testing/benchmarks/README.md
- topics/go/testing/fuzzing/README.md
Found some more broken links while reviewing Ultimate Go.
> fix up some Ultimate Go broken links

- starter-kits/http/README.md
Adding HTTP/2 to the supported protocols that net/http provides
> Updated Readme.md

- topics/README.md
Updated with new link instead of deprecated one.
> Updated Go web development new link

- topics/courses/data/TOOLING.md
Update the list of tooling used in the data training.
> update data tooling

- topics/go/README.md
This revision fixes a small typo.
> Fix statisticians typo

- topics/data/containers/example1/example1.go
- topics/data/containers/example2/example2.go
- topics/data/pipelines/README.md
- topics/data/pipelines/example1/train.json
- topics/data/pipelines/example2/predict.json
- topics/data/pipelines/exercises/template3/train.json
> update pipeline/containers topics to fix bugs

- topics/web/tls/README.md
- topics/web/tls/example2/main.go
I got the code working on my personal machine then for the example I changed it to the ardan labs domain and ip (even though it's not running this code)
> Add simple example of ACME TLS

- README.md
> Shorten the cd command with $_

- topics/web/shutdown/README.md
Fix typo on shutdown README.md
> Fix typo on shutdown README.md

- topics/go/language/constants/README.md
Match the code in the template and solution.
Fix grammar.
> Fix description in Constants exercise.

- topics/data/stats_measures/example1/example1.go
- topics/data/stats_measures/exercises/exercise1/exercise1.go
Added an n to two Media that should have been Median.
> Fixed Media to Median

- topics/data/csv_cleaning/README.md
- topics/data/csv_cleaning/example3/example3.go
- topics/data/csv_cleaning/example4/example4.go
- topics/data/csv_cleaning/exercises/exercise2/exercise2.go
- topics/data/csv_cleaning/exercises/template2/template2.go
- topics/data/json/exercises/exercise1/exercise1.go
- topics/data/sql/example2/example2.go
Current location is deprecated, moving to new definition.
> updating go-hep dep

- topics/data/evaluation/README.md
- topics/data/stats_measures/example1/example1.go
- topics/data/stats_measures/example2/example2.go
- topics/data/stats_measures/exercises/exercise1/exercise1.go
I couldn't resist the easy PR :)
> Fixed comments.

- topics/data/stats_measures/exercises/exercise1/exercise1.go
> Fixes typo

- CONTRIBUTORS
For PRs that spun out of Ultimate Data at GopherCon 2017
> Add contributors for gophercon PRs

- topics/web/basics/example6/main.go
Add a /ready handler and wait for success before starting work.
> topics/web/basics: Rework concurrency example for timing issue

- topics/web/shutdown/example1/main.go
This PR updates the shutdown example with the pattern that was implemented in the `kit` repo. It also makes a few changes:
1. Add `syscall.SIGTERM` to the list of listened signals. If the server is being managed by an auto-scaler they might send that signal instead of `SIGINT`.
2. When a shutdown is initiated we ignore the error on the `serverErrors` channel. You see `ListenAndServe` will always return a non-nil error and in the case of a user initiated shutdown it will return `http.ErrServerClosed`. In my opinion this is really a non-error. The calls to `server.Shutdown` and `server.Close` will return any useful errors coming from the listener.
> Update web class server shutdown example

- topics/go/README.md
> Fixed typo in Ultimate Go

- topics/go/design/composition/README.md
Fixing a minor typo in the quote.
> Fixing a minor typo

- topics/go/concurrency/channels/advanced/example1/example1.go
- topics/go/design/composition/grouping/example1/example1.go
- topics/go/design/composition/grouping/example2/example2.go
- topics/go/design/error_handling/example4/example4.go
- topics/go/exercises/chatbot/exercise/main.go
- topics/go/language/embedding/exercises/exercise1/exercise1.go
- topics/go/packages/encoding/example2/example2.go
- topics/go/packages/encoding/exercises/exercise1/exercise1.go
- topics/go/packages/io/advanced/example1/example1.go
- topics/web/serializers/example4/main.go
I think this set of changes is more more responsible than the previous. If there were other changes that you particularly liked from the previous PR just let me know and we'll bring them over as smaller changes.
> Println cleanup

- topics/go/language/arrays/README.md
- topics/go/language/arrays/example1/example1.go
- topics/go/language/arrays/example3/example3.go
- topics/go/language/arrays/example4/example4.go
- topics/go/language/slices/README.md
- topics/go/language/slices/example1/example1.go
- topics/go/language/slices/example2/example2.go
- topics/go/language/slices/example8/example8.go
Naming arrays and slices "strings" or "slices" or "five" is confusing to
students. Here I have used more contextually appropriate names.
> Rename some arrays and slices

- topics/go/language/variables/README.md
It might also be better to change "the other" to "another":
>The purpose of all programs and all parts of those programs is to transform data from one form to _another_.  
🤷‍♀️  :)
> Fix typo: it --> is

- topics/go/concurrency/channels/README.md
- topics/go/concurrency/channels/example5/example5.go
addressing #253 
This definitely makes the code more complicated, but it also gave me a refresher on channel directions, so that was nice.
As always, just trying to help, no worries if we don't want this merged.
> no more globals #253

- topics/go/language/interfaces/README.md
- topics/go/language/interfaces/example0/example0.go
When I first start discussing Interfaces in Go Fundamentals people will often ask "what's the point?"
I would like to start showing this code first before I show interfaces to show the kind of problem that interfaces can solve.
> Include an example of code that can be improved with interfaces.

- README.md
You suggested I update this so I thought you'd want to see it :)
> Update Jacob's profile

- topics/go/testing/strings/README.md
- topics/go/testing/strings/example1/reverse.go
- topics/go/testing/strings/example1/reverse_test.go
- topics/go/testing/strings/example2/reverse.go
- topics/go/testing/strings/example2/reverse_test.go
- topics/go/testing/strings/example3/reverse.go
- topics/go/testing/strings/example3/reverse_test.go
- topics/go/testing/strings/example4/reverse.go
- topics/go/testing/strings/example4/reverse_test.go
- topics/go/testing/strings/reverse.go
- topics/go/testing/strings/reverse_test.go
This is how I have been teaching testing and benchmarks in the Fundamentals class. I normally do this "from scratch" each time but sometimes it is hard for students to keep up so I am adding the code here for their reference.
I have the students make a package `strings` and the files `reverse.go` and `reverse_test.go`. In `reverse.go` we define a single function 
```go
func Reverse(s string) string {
return ""
}
```
We then work together to define tests for this function and an initial naive implementation. (The `example1/` folder)
That is clearly not good enough so we expand our test to be table driven and come up with our first reasonable implementation (`example2/` folder)
We continue adding test cases to our table and find that our implementation breaks on multibyte characters. Before …
> Add fundamentals testing material

- topics/go/language/arrays/README.md
In this PR I've changed "**The Myth Of Ram - Emil Ernerfeldt**" link 
http://www.ilikebigbits.com/blog/2014/4/21/the-myth-of-ram-part-i -> http://www.ilikebigbits.com/2014_04_21_myth_of_ram_1.html
> Fix a broken link

- reading/README.md
- topics/go/concurrency/channels/README.md
- topics/go/concurrency/data_race/README.md
- topics/go/concurrency/goroutines/README.md
- topics/go/concurrency/patterns/README.md
Add "Scheduling In Go - Part II" link to reading/README.md
Update links markup in topics/go/concurrency
> Update README.md files

- reading/README.md
- topics/go/language/constants/README.md
- topics/go/language/embedding/README.md
- topics/go/language/exporting/README.md
Hi there, I've made a few minor updates here:
- Fixed a few typos
- Updated a few links
> A few minor changes

- topics/go/design/composition/README.md
- topics/go/design/error_handling/README.md
- topics/go/design/packaging/README.md
- topics/go/language/interfaces/README.md
- topics/go/language/maps/README.md
- topics/go/language/methods/README.md
- topics/go/language/pointers/README.md
- topics/go/language/slices/README.md
- topics/go/language/struct_types/README.md
- topics/go/language/variables/README.md
- topics/go/packages/context/README.md
- topics/go/packages/encoding/README.md
- topics/go/packages/io/README.md
- topics/go/packages/logging/README.md
- topics/go/packages/reflection/README.md
- topics/go/profiling/README.md
- topics/go/profiling/godebug/README.md
- topics/go/profiling/mutex/README.md
- topics/go/profiling/project/main.go
- topics/go/profiling/stack_trace/README.md
- topics/go/testing/benchmarks/README.md
- topics/go/testing/fuzzing/README.md
- topics/go/testing/strings/README.md
- topics/go/testing/tests/README.md
Hi there!
In this PR I've changed broken links, unified links style ( to `[Description](link) - Author` ) and run `gofmt -s`
Thanks!
> Update links markup

- README.md
GOPATH has a sane default these days
> More copy pasteable snippets

- README.md
> Instructors

- tools/mpl/main.go
- topics/go/algorithms/data/queue/queue_test.go
- topics/go/algorithms/data/queue/student/queue_test.go
- topics/go/algorithms/data/stack/stack_test.go
- topics/go/algorithms/data/stack/student/stack_test.go
- topics/go/algorithms/fun/vlq/student/vlq.go
- topics/go/algorithms/fun/vlq/vlq.go
- topics/go/concurrency/data_race/advanced/example1/example1.go
- topics/go/concurrency/patterns/chat/chat.go
- topics/go/exercises/contributors/githubmock/main.go
- topics/go/language/embedding/README.md
- topics/go/language/embedding/exercises/exercise1/exercise1.go
- topics/go/language/embedding/exercises/template1/template1.go
- topics/go/language/methods/README.md
- topics/go/language/methods/example1/example1.go
- topics/go/packages/context/README.md
- topics/go/packages/context/exercises/exercise1/exercise1.go
- topics/go/packages/context/exercises/template1/template1.go
- topics/go/packages/encoding/README.md
- topics/go/packages/encoding/example1/example1.go
- topics/go/packages/reflection/README.md
- topics/go/packages/reflection/exercises/exercise1/exercise1.go
- topics/go/packages/reflection/exercises/template1/template1.go
- topics/go/packages/reflection/inspect/struct/struct.go
- topics/go/profiling/http_trace/README.md
- topics/go/profiling/http_trace/example1/example1.go
- topics/go/testing/benchmarks/cpu-bound/cpu.go
- topics/go/testing/benchmarks/io-bound/io.go
> Fixed most typos

- topics/go/algorithms/strings/reverse/reverse.go
- topics/go/algorithms/strings/reverse/reverse_test.go
Hi Bill,
I submitted my first example. Sorry that it took me so long to get started.
> Reverse string

- topics/go/algorithms/strings/palindrome/palindrome.go
- topics/go/algorithms/strings/palindrome/palindrome_test.go
Is string a palindrome example.
> Add example is string a palindrome

- topics/go/algorithms/data/list/list.go
Changed  **doule link list**  to **double link list**
> FIXED: Typo

- topics/go/algorithms/slices/max/max.go
- topics/go/algorithms/slices/max/max_test.go
Closes: https://github.com/ardanlabs/gotraining/issues/313
> Address issue 313

- topics/go/algorithms/tree/binary/binary.go
- topics/go/algorithms/tree/binary/example/main.go
- topics/go/algorithms/tree/binary/print.go
- topics/go/algorithms/tree/binary/traversal.go
- topics/go/algorithms/tree/binary/traversal_test.go
- Convert into a package
- Add depth first traversals
> Add traversal to binary tree

- topics/go/README.md
Signed-off-by: Zasda Yusuf Mikail <zasdaym@gmail.com>
> Fix typo algorthims -> algorithms

- Opening.md
> Bumping up of the latest Go version

- topics/go/generics/11-hash-table/generic.go2
First of all, thank you so much for these resources they are really helpful to get an understanding of how Generics are going to work in Go I learned a lot 🙇 
---
There is a mixture of spaces and tabs in the file that gets rendered as
if things aren't intended properly.
> Indent generic hash function with tabs

- reading/README.md
Adds a new book: Concurrency in Go by Katherine Cox-Buday
> Concurrency in Go [Book]

- topics/go/algorithms/searches/binarysearch/binarysearch.go
- topics/go/algorithms/searches/binarysearch/binarysearch_test.go
- topics/go/algorithms/searches/interpolationsearch/interpolationsearch.go
- topics/go/algorithms/searches/interpolationsearch/interpolationsearch_test.go
- topics/go/algorithms/searches/jumpsearch/jumpsearch.go
- topics/go/algorithms/searches/jumpsearch/jumpsearch_test.go
- topics/go/algorithms/searches/linearsearch/linearsearch.go
- topics/go/algorithms/searches/linearsearch/linearsearch_test.go
I added some simple searching algorithms with test
- Binary Search
- Linear Search
- Double Linear Search
- Jump Search
- Interpolation Search
> Searches Algorithm

- topics/go/algorithms/searches/binarysearch/binarysearch.go
- topics/go/algorithms/searches/binarysearch/binarysearch_test.go
- topics/go/algorithms/searches/interpolationsearch/interpolationsearch.go
- topics/go/algorithms/searches/interpolationsearch/interpolationsearch_test.go
- topics/go/algorithms/searches/jumpsearch/jumpsearch.go
- topics/go/algorithms/searches/jumpsearch/jumpsearch_test.go
- topics/go/algorithms/searches/linearsearch/linearsearch.go
- topics/go/algorithms/searches/linearsearch/linearsearch_test.go
I am working on making more cleaner the codes and tests of searching algorithms.
> fixed search algorithms

- CONTRIBUTORS
- topics/go/algorithms/searches/linearsearch/linearsearch.go
change if statement to switch in doubleLinearSearchIterative
> fixed doubleLinearSearchIterative 

- topics/go/algorithms/sorting/selection/selection.go
- topics/go/algorithms/sorting/selection/selection_test.go
Added selection sort algorithm with test and benchmark with the `iterative` process.
> Selection Sort Algorithm

- topics/go/algorithms/sorting/quick/quick.go
- topics/go/algorithms/sorting/quick/quick_test.go
- topics/go/algorithms/sorting/selection/selection.go
- topics/go/algorithms/sorting/selection/selection_test.go
I added quick sort algorithm implementation with test and benchmark.
> Quick Sort

- topics/go/algorithms/sorting/insertion/insertion.go
- topics/go/algorithms/sorting/insertion/insertion_test.go
I added an insertion sort algorithm with the testcase.
> insertion sort algorithm

- reading/README.md
> Add release doc for v1.17

- README.md
Some links were broken due to sections being reworked in the document.
> Fix broken Links in Readme

- topics/go/videos/miki/shorts/cleanup/cleanup_test.go
- topics/go/videos/miki/shorts/compound_key/main.go
- topics/go/videos/miki/shorts/expandenv/main.go
- topics/go/videos/miki/shorts/fmt_loc/main.go
- topics/go/videos/miki/shorts/fmt_star/main.go
- topics/go/videos/miki/shorts/fold/main.go
- topics/go/videos/miki/shorts/go.mod
- topics/go/videos/miki/shorts/http_flusher/main.go
- topics/go/videos/miki/shorts/io_multi/main.go
- topics/go/videos/miki/shorts/is_alive/main.go
- topics/go/videos/miki/shorts/json_binary/main.go
- topics/go/videos/miki/shorts/label/main.go
- topics/go/videos/miki/shorts/make/main.go
- topics/go/videos/miki/shorts/net_ip/main.go
- topics/go/videos/miki/shorts/pipe/main.go
- topics/go/videos/miki/shorts/raw_string/main.go
- topics/go/videos/miki/shorts/regexp_fn/main.go
- topics/go/videos/miki/shorts/server/main.go
- topics/go/videos/miki/shorts/stringer/role.go
- topics/go/videos/miki/shorts/test_main/main_test.go
- topics/go/videos/miki/shorts/url_query/main.go
Repo for code on "shorts" videos for YouTube
> shorts YouTube videos
