- 11-http/api/app/context.go
- 11-http/api/ctrls/users.go
- 11-http/api/routes/routes.go
Notes:
* `http.Error` must not be used to send JSON: its documentation specifically states the message must be plaintext.
* JSON error output unified. In particular, field validation errors no longer return an array as the root value, and Content-Type and Content-Length fields are set.
* The `http.ResponseWriter` is embedded in `*Context`, making it more convenient to use for special cases (Context is now itself a ResponseWriter).
> http: dedup, simplification.

- 07-concurrency_channels/03-channels/example3/example3.go
If `isNecessary` returns `false` for all calls (which is reasonable), then `err := <-ch` (on [line 55](https://github.com/ArdanStudios/gotraining/blob/54e72136eaac33aacc6dcd18cb7d79f305c56556/07-concurrency_channels/03-channels/example3/example3.go#L55)) will cause something like:
```shellsession
$ ./example3
2015/05/28 18:06:02 Inserts Started
fatal error: all goroutines are asleep - deadlock!
goroutine 1 [chan receive]:
main.performInserts()
~/ardan-studios-gotraining/gotraining/07-concurrency_channels/03-channels/example3/example3.go:55 +0x230
main.main()
~/ardan-studios-gotraining/gotraining/07-concurrency_channels/03-channels/example3/example3.go:28 +0x1b
```
A solution is to remove the `if/break` construct (starting on [line …
> Fixed potential deadlock/infinite loop when isNecessary returns false

- 10-standard_library/02-encoding/example3/example3.go
We do not need to make a conversion to String when using fmt.Printf("%s") because it %s supports byte slice and/or strings.
> Unecessary conversion from byte slice to string

- 10-standard_library/02-encoding/readme.md
I believe the link for "Custom Marshaler and Unmarshler" should be:
https://github.com/ArdanStudios/gotraining/blob/master/10-standard_library/02-encoding/example4/example4.go
> Wrong link for Custom Marshaler and Unmarshler

- 03-methods_interfaces_embedding/03-embedding/exercises/exercise1/exercise1.go
We return the boolean directly instead of wrapping it in an `if` statement.
> Simplify the search methods

- 13-http/api/app/context.go
It was encoding the marshaled interface and the output (to the consumer) would look something like `eyJoZWxsbyI6ImFzZGZhc2RmIn0=` which clearly isn't JSON.
I've also corrected the tab alignment of the comments.
> Respond should actually encode the JSON now

- 13-http/api/app/app.go
- 13-http/api/app/context.go
- 13-http/api/middleware/request_logger.go
Adding just one type and one method to the public API gets some basic middleware support. This would probably get placed in a middleware package with each middleware getting its own file. 
Depending where the middleware chooses to call the provided `app.Handler` you get a before, around, or after middleware. The middleware also has the option of canceling the execution chain (think authorization) meaning that the handler for the given route only needs to concern itself with the happy path.
What this doesn't provide is a way to apply some set of middleware only to a subset of routes, but even so, I think it's a good example of an approach. 
A basic middleware would look something like:
```go
// middleware/yo.go
package middleware
import (
"fmt" …
```
> Add middleware support

- topics/sched_trace/README.md
Link pointed to source file godebug.go, but its called trace.go.
> Fixed broken link to source file.

- tools/markdown-playground-links/README.md
- tools/markdown-playground-links/main.go
This tool processes markdown files from the training materials to automatically
update "Go Playground" links with the latest code from the linked samples.
It will find mardown like the following and automatically update it:
```
The following link will automatically be updated
[markdown-playground-links](main.go) ([Go Playground](http://play.golang.org/p/X8oPoc-i9L))
The program searches for a link followed by a "([Go Playground](.*))" link.
```
You can use an empty playground link and it will be automatically popullated
with the right link.
Simply run `markdown-playground-links` with a list of files you want to process.
```
markdown-playground-links topics/constants/README.md
markdown-playground-links **/*.md
```
> First version of markdown-playground-links tool

- Dockerfile
- README.md
This PR includes
- adding a Dockerfile to allow starting to use the material in a docker container
- updating README with instructions on how to build and run gotraining container
Note: Using docker container will enable any user to start using the gotraining material right away without having to install and setup go. And it can be easily removed after use.
> Added Dockerfile and updated README on how to use docker container

- tools/mpl/README.md
- topics/composition/README.md
- topics/composition/example5/example5.go
- topics/embedding/README.md
- topics/exporting/README.md
- topics/interfaces/example2/example2.go
- topics/methods/README.md
- topics/methods/example1/example1.go
- topics/slices/README.md
- topics/slices/example3/example3.go
- General spelling and grammar fixes
- In `topics/exporting/README.md` there is a link to the lib for
`example4` where it should have be `example5`
- In `topics/methods/example1/example1.go` we show changing a value from
`email.com` to `gmail.com` which is only one letter different. It
seems like it would be easy to miss the difference so I changed it to
`hotmail.com` :)
> Spelling, wording, link, and clarification fixes

- topics/error_handling/README.md
This is definitely a subtle bug.  An answer example with an inner and outer
print of the type shows how the unexpected comparison happens in a strongly
typed language.
Signed-off-by: Tim Pepper <timothy.c.pepper@linux.intel.com>
> add answer example for "find the bug" in error_handling

- topics/profiling/README.md
- topics/profiling/project/main.go
Mentioned this briefly to William at the pre-kickoff party and he requested an email reminder; I figured a PR would be a more useful reminder (and a good use of a little hack day time) :)
During the Advanced Go workshop at GopherCon, the execution tracer example mentioned special code required to capture traces, and a command line arg was used to enable tracing for the process lifetime.  That's not actually required; the default endpoints exposed by `net/http/pprof` also expose execution trace captures, in an ad-hoc fashion.  This allows capturing more targeted traces of a shorter duration (vital given the 'information overload' nature of execution traces).
I've updated the code and the brief description in the README.md.
Thanks much for the training and making this content open sourced!
> Leverage pprof endpoints for execution traces

- topics/profiling/godebug/schedtrace/README.md
The link to Dave Cheney's website was backwards (name where the url should go).
> Fixes link to Dave Cheney's website

- topics/profiling/README.md
- topics/profiling/godebug/schedtrace/README.md
This PR changes to `go-wrk -m` instead of `-M.` The lowercase flag is the one for sending a specific HTTP method as of go-wrk as of this commit: https://github.com/adjust/go-wrk/commit/71f7f2794f958abbaf6538df7d708a8873eb1756
`go-wrk -M` doesn't work
> change `go-wrk -M` to `go-wrk -m`

- topics/profiling/benchmarks/stream.go
- topics/profiling/benchmarks/stream_test.go
This PR adds two more example functions to the elvis stream benchmarking/profiling section. These two new examples take io.Reader to effectively work on an infinite stream, rather than a slice of bytes.
The third example is effectively the same as example two, but uses bufio instead of bytes as the reader into the io.Reader stream.
The fourth example is effectively the same, but reads directly to a buffer of our own, and skips the UnreadByte call by simply re-using the buffer in the case of a match.
In addition, the test file has been changed to allow all the benchmarks to start at zero allocations in the benchmark itself, isolating all work to the processing functions. This gives more accurate output in terms of allocations and time spent.
> Add two more stream profiling examples.

- README.md
Link for @ianfoo tweet actually pointed to a @c4milo's tweet.
> Correct link to tweet in Twitter section.

- courses/quick_tour/HTTP.md
Instructions state to create file, "webserver.go"
Proper command should be `go run webserver.go`
Old command states command is `go run website.go`
> Fix http go run command.

- courses/quick_tour/CONCURRENCY.md
- topics/web/apis/example2/main_test.go
- topics/web/apis/example3/main.go
- topics/web/apis/example4/main.go
- topics/web/auth/example1/main_test.go
- topics/web/consuming/example3/main_test.go
- topics/web/consuming/example5/main_test.go
- topics/web/consuming/example6/main_test.go
- topics/web/muxers/example3/main.go
- topics/web/posts/example4/main_test.go
- topics/web/sessions_cookies/example1/main_test.go
- topics/web/sessions_cookies/example2/main_test.go
Some code was broken because `github.com/labstack/echo` changed their API in a recent version. Those were updated.
Some other tests were broken in #171 because the `*http.Request` created by `httptest.NewRequest` is intended to mimic a server request. To make a client request you have to keep using `http.NewRequest`.
> Fix all tests under topics/web

- topics/language/methods/README.md
Updated Playground link for example3. Changed the spelling from Complier to Compiler on line 39.
> Updated playground link for example3

- topics/web/serializers/example3/main.go
- topics/web/serializers/example4/main.go
- topics/web/serializers/example4/main_test.go
The test for `topics/web/serializers/example4` sometimes fails seemingly at random. I looked into it and it's because we build our custom xml encoder by ranging over a map which is not guaranteed to be in any particular order. Since we include five elements in our map there are possibly 120 combinations (though in reality I don't think we'd ever actually see all 120). The test code was looking for results in one of four combinations and most of the time that was good enough but sometimes it wasn't.
I would like to make the order of the elements deterministic. This PR includes one approach that uses a closure to append each element to the token slice and we just call it up to 5 times (no looping involved). I am willing to entertain other approaches if this code is not clear to students.
> Control the order of elements in custom xml encoder

- templates/layout.tmpl
- topics/courses/data/data_gathering/README.md
- topics/courses/data/introduction/README.md
- topics/courses/data/matrices/README.md
- topics/courses/data/prediction/README.md
- topics/courses/data/statistics/README.md
- topics/courses/go/packages/README.md
The "Courses" link in the header of the root page is broken. Just added 'topic' to the link path.
> fix 'Courses' link in layout

- starter-kits/http/cmd/apid/main.go
- topics/web/shutdown/example1/main.go
- Set timeout as a const
- Change control flow of shutdown vs close
- Rename log messages from "closer" to "shutdown"
> Revise web server shutdown examples

- topics/web/serializers/README.md
- topics/web/serializers/example5/main.go
I added an example to show two problems I see often when marshalling JSON
1. Attempting to marshal unexported fields
2. Marshalling a zero value (nil) slice. This isn't necessarily wrong but if you're serving this in a web API it is annoying for your clients to do a null check before accessing an array field. In JS for example if you try to check `.length` or iterate over a null value you'll get a TypeError at runtime.
> topics/web/serializers: Add an example showing common JSON mistakes

- topics/go/language/embedding/exercises/exercise1/exercise1.go
- topics/go/language/embedding/exercises/template1/template1.go
The typical convention for search code is to use "needle" and
"haystack" words for the search term and the thing to search in. This
makes the answer a lot easier to read. I've changed the comments in
the code as well to reflect the verbiage change.
> Use "needle" and "haystack" terminology.

- .travis.yml
- starter-kits/http/cmd/apid/tests/user_test.go
With a little configuration we can ask Travis to launch a new MongoDB for each test run. This prevents false positives from leftover data in the Mlab instance.
> Use a Travis hosted instance of MongoDB for CI

- starter-kits/http/cmd/apid/main.go
- topics/web/shutdown/example1/main.go
The docs of signal.Notify say
Package signal will not block sending to c: the caller must ensure
that c has sufficient buffer space to keep up with the expected
signal rate. For a channel used for notification of just one signal
value, a buffer of size 1 is sufficient.
In the implementation of the signal package they're doing this
// send but do not block for it
select {
case c <- sig:
default:
}
> Use buffered channels when listening for OS signals

- topics/web/middleware/README.md
- topics/web/middleware/example3/handlers.go
- topics/web/middleware/example3/main.go
- topics/web/middleware/example3/mw.go
The other middleware examples introduce the concepts but this example is intended to be more "complete" in showing more of how I would actually write something using middleware. It also introduces two very useful community packages: 
- `github.com/justinas/alice` which is a super lightweight way of chaining MW
- `github.com/gorilla/handlers` which is a collection of very useful and commonly needed middleware such as logging requests in the Apache log format, handling panic, gzipping responses, activating CORS, etc.
This example also shows how to have additional middleware run for certain routes which is a common question when I get to this section.
> Add a more complete middleware example using Alice and gorilla/handlers

- topics/data/csv_cleaning/README.md
It's hard to get the regular go installer to work with gcc on Windows. So it's either recommended to install go / gcc with msys2 or just not use cgo.
> Make a note about ql requiring cgo or a purego tag

- topics/go/concurrency/goroutines/README.md
- topics/go/concurrency/goroutines/example1/example1.go
- topics/go/concurrency/goroutines/example3/example3.go
- Use `r` instead of `rune` for variable names. Using a type name as a variable name is a smell.
- `<= 'z'` seems more clear on intent than `< 'a'+26`
> Clarify some rune counting loops

- topics/go/design/composition/README.md
- topics/go/design/composition/decoupling/example6/example6.go
Decoupling example 6 includes an unnecessary conversion of the `Xenia` and `Pillar` types to `Puller` and `Storer`. However Xenia and Pillar already fulfill the `Puller` and `Storer` interfaces and thus don't need the explicit conversion.
> Remove unnecessary conversion

- reading/README.md
Fixes the release date for 1.9, per source: https://blog.golang.org/go1.9
Thanks for this amazing resource of links!
> Typo in 1.9 release date

- topics/go/design/error_handling/example2/example2.go
301 is permanent
302 is temporary
Should only check again if its 302? but then its not really permanent.
Simplified by saying Page moved instead.
> This example is confusing as written

- topics/go/language/slices/README.md
- topics/go/language/slices/example3/example3.go
When covering the "Slices of Slices" section we show how slices can share a backing array and how this can potentially be dangerous. I added a third slice in this example that uses `copy` to ensure the new slice has a different backing.
Maybe this should be moved to a whole new example file?
> Show how to copy a slice without sharing a backing array

- Dockerfile
- README.md
Change the Dockerfile CMD from `/bin/bash` to `/bin/sh`, since the bash shell isn't installed in the docker base image we're using (`golang:1.9.1-alpine3.6`).
Before this change, running a container based on the `ardanlabs/gotraining` image would fail with a `/bin/bash: not found` error by default.
> Fix Dockerfile CMD

- topics/go/language/slices/README.md
- topics/go/language/slices/example4/example4.go
Having it all on one line is confusing when people are learning append.
> Change format of example append call

- topics/go/language/pointers/README.md
- topics/go/language/pointers/example2/example2.go
- topics/go/language/pointers/example3/example3.go
In example3 we have a `*u` which dereferences a pointer to get to the
underlying struct value. This is good to know but I rarely ever do this.
Instead if a have a pointer variable `u` and I want the `name` property
I will use `u.name` which automatically deference the pointer.
I show this here because it's about this point in the training that
students are envisioning a life of frequent manual pointer dereference
but the reality is more convenient.
I also tweaked the formatting a bit so the output of example3 looks like
```
0xc42008e180    {name:Bill email:bill@ardanlabs.com logins:0}
Name: "Bill" Email: "bill@ardanlabs.com" Logins: 0
&logins[0xc4200a4020] logins[0xc42008e1a0] *logins[1]
0xc42008e180    {name:Bill email:bill@ardanlabs.com logins:1}
Name: "Bill" Email: "bill@ardanlabs.com" …
```
> pointers: Show how Go will conveniently dereference pointers to structs

- topics/go/language/embedding/README.md
- topics/go/language/embedding/exercises/exercise1/exercise1.go
- topics/go/language/embedding/exercises/template1/template1.go
This is still basically the same exercise as before except it no longer feels like we are trying to emulate inheritance like we were with Sport+Hockey.
We start with a type `Feed` that has two methods `Count()` and `Fetch()`.  We ask the student to create a type `CachingFeed` which overrides the `Fetch` method.
We then pass both a value of type `*Feed` and a value of type `*CachingFeed` into a function which depends on the interface
```go
// FetchCounter is the behavior we depend on for our process function.
type FetchCounter interface {
Fetch(key string) (Document, error)
Count() int
}
```
> Rework embedding example.

- topics/go/concurrency/channels/README.md
- topics/go/concurrency/channels/example1/example1.go
This PR fixes a minor output bug with `emps` counter.
For instance an output with `emps=5` on [example1.go:126](https://github.com/ardanlabs/gotraining/blob/master/topics/go/concurrency/channels/example1/example1.go#L126)
```sh
employee : sent signal : 0
paper
manager : recv'd signal : 5
employee : sent signal : 2
paper
manager : recv'd signal : 4
employee : sent signal : 1
paper
manager : recv'd signal : 3
paper
manager : recv'd signal : 2
employee : sent signal : 4
employee : sent signal : 3
paper
manager : recv'd signal : 1
```
`employee` sends signals starting from `0` but `manager` receives starting from `1`
P.S. 
Does it worth to change the format to smth like this?
```sh
employee[0]: sent signal "paper"
employee[1]: sent signal "paper"
manager: recv'd signal "paper" from …
```
> A minor fix of fanOut/fanOutSem funcs

- topics/go/language/pointers/README.md
- topics/go/language/pointers/example4/example4.go
`createUserV2` returns a pointer and the main function should print it directly to show it is the same address as the one printed inside `createUserV2` because it is allocated on heap, the main function was printing the address of the pointer, so the output was confusing, V2 and u2 should be the same.
Before
````text
V1 0x41c770
V2 0x40c030
u1 0x41c7a0 u2 0x41c79c
````
After
````text
V1 0x41c770
V2 0x40c030
u1 0x41c7a0 u2 0x40c030
`````
> Print pointer directly in escape analysis example

- topics/go/concurrency/goroutines/README.md
- topics/go/concurrency/goroutines/example2/example2.go
This modified version of goroutines/example2 does sha1+hex for each number in a single loop. Initially it only loops up to 10 and the output is this
```$ go run example2.go
Create Goroutines
Waiting To Finish
B: 00001: 356a192b7913b04c54574d18c28d46e6395428ab
B: 00002: da4b9237bacccdf19c0760cab7aec4a8359010b0
B: 00003: 77de68daecd823babbb58edb1c8e14d7106e83bb
B: 00004: 1b6453892473a467d07372d45eb05abc2031647a
B: 00005: ac3478d69a3c81fa62e60f5c3696165a4e5e6ac4
B: 00006: c1dfd96eea8cc2b62785275bca38ac261256e278
B: 00007: 902ba3cda1883801594b6e1b452790cc53948fda
B: 00008: fe5dbbcea5ce7e2988b8c69bcfdfde8904aabc1f
B: 00009: 0ade7c2cf97f75d009975f4d720d1fa6c19f4897
B: 00010: b1d5781111d84f7b3fe45a0852e59758cd7a87e5
Completed B
A: 00001: 356a192b7913b04c54574d18c28d46e6395428ab
A: 00002: …
```
> Use a simpler program for showing goroutine time slicing

- topics/go/concurrency/data_race/README.md
- topics/go/concurrency/data_race/example1/example1.go
- topics/go/concurrency/data_race/example2/example2.go
- topics/go/concurrency/data_race/example3/example3.go
Loop variable `count` too similar to package-level variable `counter`, taking attention away from the lesson in these examples.
> Readability improvements

- topics/go/concurrency/data_race/README.md
- topics/go/concurrency/data_race/example4/example4.go
Hopefully (!!) this shows you've taught me well...
This PR fixes incorrect output of the goroutine ID. Typically the output shows all goroutine's have an ID of '8' which is clearly not what's intended. 
Cause:
```
$ go vet
./example4.go:49:12: loop variable i captured by func literal
```
Using the Go race detector:
```
$ go build -race
$ ./example4
==================
WARNING: DATA RACE
Read at 0x00c0000d6010 by goroutine 8:
main.main.func2()
/Users/dan/working/go/src/github.com/DanHam/gotraining/topics/go/concurrency/data_race/example4/example4.go:49 +0x38
Previous write at 0x00c0000d6010 by main goroutine:
main.main()
/Users/dan/working/go/src/github.com/DanHam/gotraining/topics/go/concurrency/data_race/example4/example4.go:46 +0x114
Goroutine 8 (running) created at:
main.main() …
```
> Fix goroutine id output

- topics/go/README.md
The mention "48 critical failures were found in a study looking at a couple hundred bugs in Cassandra, HBase, HDFS, MapReduce, and Redis." is valuable but I didn't find the source of that study in this file. I found it as a pdf, if you prefer to link other type of medias just let me know.
> Add reference about study in cloud systems

- reading/README.md
Getting a 
```
NOT_FOUND: Requested entity was not found
```
When clicking on `https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters`.
This adds .md to retrieve.
> corrects generics draft design link

- reading/README.md
I found [Quick intro to Go assembly](https://blog.hackercat.ninja/2018/quick_intro_to_go_assembly/)'s URL is changed and encountered 404 when I visited this URL.
So I wrote this pull request in order to fix this 404 error.
> fix URL in reading

- CONTRIBUTORS
- topics/go/packages/context/README.md
- topics/go/packages/context/exercises/exercise1/exercise1.go
I've found a weird thing. The channel receives a pointer to a user structure, but on the line 76 the pointer of a pointer has been taken and passed as an argument to the sendResponse method. Was it done on purpose or I fixed it here correctly?
> fix: removed taking pointer of a pointer

- topics/go/testing/tests/README.md
The name is "Kevlin", not "Kevin". See https://twitter.com/KevlinHenney
> Fix typo in Kevlin Henney's name

- topics/go/language/struct_types/advanced/example1/example1.go
- tbp should three byte of padding not two.
> Comment is fixed - topics/go/language/struct_types/advanced/example1/example1.go

- topics/go/algorithms/data/tree/binary/binary.go
Thank you for the work on this. It was nice to study binary tree implementation in Go.
This change disallows duplicates in the binary tree.
The following values:
```
values := []int{65, 65, 65, 65, 65, 45, 35, 75, 85, 78, 95}
```
Will produce the following binary tree.
```
> go run main.go 
75
/      \
45      85
/  \    /  \
35  65  78  95
Pre-order : [75 45 35 65 85 78 95]
In-order  : [35 45 65 75 78 85 95]
Post-order: [35 65 45 78 95 85 75]
```
> Prevent duplicates in binary tree

- reading/README.md
This commit removes a repeated link to a resource that was already mentioned on line 388.
> Removed repeated link

- topics/go/testing/benchmarks/caching/caching.go
A simpler way to create a linked list by chaining it backwards.
> A simpler way to create linked list

- topics/go/profiling/trace/README.md
The go tool trace link is broken. 
This PR updates the link to something on web archive, which I found on Will Sewell's blog [here](https://willsewell.com/blog.html)
> Update go/profiling/trace README.md

- topics/go/README.md
Got moved there from medium, see:
https://web.archive.org/web/20181225050941/https://medium.com/@rakyll/interface-pollution-in-go-7d58bccec275
> fix dead link to "Interface pollution in Go" blog
